namespace SmallNetworkIDS.Core.Models;

public enum AlertSeverity
{
    Low,
    Medium,
    High,
    Critical
}

public enum AlertType
{
    PortScan,
    DDoSFlood,
    SynFlood,
    AnomalousTraffic
}

/// <summary>
/// Represents a security alert generated by the IDS
/// </summary>
public class AlertEvent
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    public AlertType Type { get; set; }
    public AlertSeverity Severity { get; set; }
    public string SourceIp { get; set; } = string.Empty;
    public string DestinationIp { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public double AnomalyScore { get; set; }
    public string? SuggestedAction { get; set; }
    
    // Related flow data
    public NetworkFlow? RelatedFlow { get; set; }
    
    public override string ToString()
    {
        return $"[{Timestamp:HH:mm:ss}] [{Severity}] {Type}: {Description} (Score: {AnomalyScore:F2})";
    }
}
